--exectute this first
Create Database ExpenseTracker;

USE ExpenseTracker

Create table T_USER
(
USER_ID int IDENTITY(1,1) PRIMARY KEY,
USERNAME NVARCHAR(20),
EMAIL NVARCHAR(50),
AUTHORITY_TYPE int,
COMPANY_ID int,
MAIL_ADDRESS NVARCHAR(50)
,PASSWORD NVARCHAR(10)
);

Create table T_SUPPLIER
(
SUPPLIER_KEY_ID int IDENTITY(1,1) PRIMARY KEY,
COMPANY_ID INT
,SHOP_ID INT 
,SUPPLIER_NAME NVARCHAR(50)
,CONTACT_NUMBER NVARCHAR(50)
,MAIL NVARCHAR(50)
,REG_USER INT
,REG_DTM NVARCHAR(50)
,UPD_USER INT
,UPD_DTM NVARCHAR(50)
)
Create table T_EXPENSES_SALARY(
SALARY_KEY_ID int IDENTITY(1,1) PRIMARY KEY
,COMPANY_ID INT
,SHOP_ID INT
,PAID_DATE_MONTH VARCHAR(50)
,PAID_DATE_YEAR VARCHAR(50)
,TOTAL_SALARY VARCHAR(50)
,UPD_USER INT
);
Create table T_EXPENSES_SALARY_DETAIL(
SALARY_KEY_ID int IDENTITY(1,1) PRIMARY KEY
,SALARY_DETAIL_KEY_ID INT
,COMPANY_ID INT
,EMPLOYEE_KEY_ID INT
,ALLOWANCE INT
,DEDUCTION INT
,NET_SALARY INT
,SALARY  INT
);